import type { Metadata } from 'next'
import './globals.css'
import { fontBody } from './font'
import { Header } from '@/components/header/nav'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
  title: 'Imobiliaria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = cookies().get('token')?.value
  const authentication =
    token !== undefined && token.length >= 49 && token.length <= 53
  return (
    <html lang="pt-br" className={fontBody.className}>
      <body className="antialiased scroll-smooth">
        <Header authentication={authentication} />
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  )
}
