import type { Metadata } from 'next'
import './globals.css'
import { fontBody } from './font'
import { Header } from '@/components/header/nav'

export const metadata: Metadata = {
  title: 'Imobiliaria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={fontBody.className}>
      <body className="antialiased scroll-smooth">
        <Header />
        <div className="max-w-[1200px] mx-auto">{children}</div>
      </body>
    </html>
  )
}
