import type { Metadata } from 'next'
import './globals.css'
import { fontBody } from './font'
import { HeaderOff } from '@/components/header/navOff'
import { cookies } from 'next/headers'
import { HeaderOn } from '@/components/header/navOn'

export const metadata: Metadata = {
  title: 'Imobiliaria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = cookies().get('token')?.value
  const authentication =
    token !== undefined && token.length >= 49 && token.length <= 53
  return (
    <html lang="pt-br" className={fontBody.className}>
      <body className="antialiased scroll-smooth">
        {authentication ? <HeaderOn /> : <HeaderOff />}
        <div className="max-w-[1200px] mx-auto">{children}</div>
      </body>
    </html>
  )
}
